### ISSUE TITLE
Question about running the demo code

### ISSUE THREAD

**Issue by fyabc** [KeenThera/SECSE#2]
Hi authors,

I have tried to run your demo code in README.md, but got some errors.

## Command

```bash
python /home/xxx/workspace/off-SECSE/secse/run_secse.py --config ./config.ini
```

## Output

```text
 **************************************************************************************** 
       ____    _____    ____   ____    _____ 
      / ___|  | ____|  / ___| / ___|  | ____|
      \___ \  |  _|   | |     \___ \  |  _|  
       ___) | | |___  | |___   ___) | | |___ 
      |____/  |_____|  \____| |____/  |_____|

******************************************************************
Input fragment file: /home/xxx/workspace/off-SECSE/fy-run/demo001/ligand.smi
Target grid file: /home/xxx/workspace/off-SECSE/fy-run/demo001/receptor.pdbqt
Workdir: /home/xxx/workspace/off-SECSE/fy-run/demo001/

Step 1: Docking with Autodock Vina ...
/home/xxx/workspace/off-SECSE/secse/evaluate/ligprep_vina_parallel.sh /home/xxx/workspace/off-SECSE/fy-run/demo001/generation_0 /home/xxx/workspace/off-SECSE/fy-run/demo001/ligand.smi /home/t-yafan/workspace/off-SECSE/fy-run/demo001/receptor.pdbqt 20.9 -10.4 3.0 20.0 20.0 25.0 10
find /home/xxx/workspace/off-SECSE/fy-run/demo001/generation_0/sdf_files -name "*sdf" | xargs -n 100 cat > /home/xxx/workspace/off-SECSE/fy-run/demo001/generation_0/docking_outputs_with_score.sdf
Docking time cost: 0.11 min.
Step 2: Ranking docked molecules...
9 cmpds after evaluate
The evaluate score cutoff is: -9.0
9 final seeds.

 ************************************************** 
Generation  1 ...
Step 1: Mutation
Traceback (most recent call last):
  File "/home/xxx/workspace/off-SECSE/secse/run_secse.py", line 70, in <module>
    main()
  File "/home/xxx/workspace/off-SECSE/secse/run_secse.py", line 55, in main
    workflow.grow()
  File "/home/xxx/workspace/off-SECSE/secse/grow_processes.py", line 159, in grow
    header = mutation_df(self.winner_df, self.workdir, self.cpu_num, self.gen)
  File "/home/xxx/workspace/off-SECSE/secse/growing/mutation/mutation.py", line 166, in mutation_df
    mutation = Mutation(5000, workdir)
  File "/home/xxx/workspace/off-SECSE/secse/growing/mutation/mutation.py", line 29, in __init__
    self.load_common_rules()
  File "/home/xxx/workspace/off-SECSE/secse/growing/mutation/mutation.py", line 50, in load_common_rules
    c.execute(sql)
sqlite3.OperationalError: no such table: B-001
```

It seems that the file `secse/growing/mutation/rules_demo.db` is missing in the repo. How can I fix it?

Thanks!

**Comment by ChongLu121** [comment]
Hi Fan,

the DB file was uploaded. You may run the same command again.

Best,
Chong

**Comment by fyabc** [comment]
Thanks!

Could you please provide the demo PDBQT file?

**Comment by ChongLu121** [comment]
> Thanks!
> 
> Could you please provide the demo PDBQT file?
[PHGDH_6RJ3_for_vina.pdbqt.zip](https://github.com/KeenThera/SECSE/files/8137634/PHGDH_6RJ3_for_vina.pdbqt.zip)

**Comment by fyabc** [comment]
Thank you very much! I can run the code now.
I have an extra question:
I have 100 protein PDBQT files, and I want to generate some molecules from each protein. How can I choose the initial fragment SMILES?
Thanks!

**Comment by ChongLu121** [comment]
We provide a  fragment database containing up to 12 heavy atoms with MW ranging from 50 Da to 210 Da.
Download link  https://figshare.com/articles/dataset/fragment_space/17142236
If you don't have any preference for the initial fragments, you can randomly sample some as input.
In our paper, the initial seed was benzene, which is also an option.

Fragments can also be selected based on your expected interactions if you have any hypothesis about the binding mode of the proteins.
