### ISSUE TITLE
filter.csv problem

### ISSUE THREAD

**Issue by zemanet2020** [KeenThera/SECSE#8]
I installed SECSE on May 11, 2023 as instructed in README.
I made appropriate changes in config file as below (demo/demo.ini):

```
[DEFAULT]
project_code = PHG
workdir = /SECSE/result
fragments = /SECSE/demo/demo_1020.smi
num_gen = 5
num_per_gen = 50
seed_per_gen = 10
start_gen = 0
docking_program = autodock-gpu
cpu = 10
gpu = 3
rule_db = 0

[docking]
target = /SECSE/demo/PHGDH_6RJ3_for_vina.pdbqt
x = 20.9
y = -10.4
z = 3.0
box_size_x = 20
box_size_y = 20
box_size_z = 25
RMSD = 2
delta_score = -1.0
score_cutoff = -9

[deep learning]
mode = 2
dl_per_gen = 100
dl_score_cutoff = -9

[properties]
MW = 500
logP_lower = 0.5
logP_upper = 7
chiral_center = 3
heteroatom_ratio = 0.35
rotatable_bound_num = 5
rigid_body_num = 2

```

Then I ran:
    python secse/run_secse.py --config demo/demo.ini

I got the following error messages:

```
Generation  1 ...
Step 1: Mutation
Step 2: Filtering all mutated mols
Filter runtime: 0.01 min.
Traceback (most recent call last):
  File "secse/run_secse.py", line 81, in <module>
    main()
  File "secse/run_secse.py", line 66, in main
    workflow.grow()
  File "/opt/modeling/molecule-generation/SECSE/secse/grow_processes.py", line 213, in grow
    self._filter_df = pd.read_csv(os.path.join(self.workdir_now, "filter.csv"), header=None)
  File "/opt/anaconda310/envs/secse/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda310/envs/secse/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda310/envs/secse/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/anaconda310/envs/secse/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/anaconda310/envs/secse/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/anaconda310/envs/secse/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/opt/anaconda310/envs/secse/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

```

I checked if "filter.csv" file exists:

```
$ ls -R result/
result/:
generation_0  generation_1

result/generation_0:
best_fragment_gen_0.smi  docked_gen_0.csv  docking_outputs_with_score.sdf  sdf_files  vina_config.txt

result/generation_0/sdf_files:
f1-dp1.sdf  f1-dp2.sdf  f1-dp3.sdf  f2-dp1.sdf  f2-dp2.sdf  f2-dp3.sdf  f3-dp1.sdf  f3-dp2.sdf  f3-dp3.sdf

result/generation_1:
filter.csv  generation.csv  seed_fragments.smi
```

Yes, "filter.csv" file is there but it was empty.

Please let me know what would cause this problem.

**Comment by ChongLu121** [comment]
Hi  @zemanet2020 ,

Thank you for reporting the issue.
Could you please confirm if the "generation.csv" and "seed_fragments.smi" files in the "result/generation_1" directory are also empty?

Additionally, to better understand the issue, could you provide a list of all the packages installed in your Conda environment named "secse"? You can obtain the list by running the following command in your terminal: `$ conda list -n secse`


Best,
Chong

**Comment by sistar2020** [comment]
Here's the listing of "result" directory:
```
$ ls -lR result
total 8
drwxrwxr-x 3 coolguy coolguy 4096  5월 12 01:23 generation_0
drwxrwxr-x 2 coolguy coolguy 4096  5월 12 01:23 generation_1

./generation_0:
total 28
-rw-rw-r-- 1 coolguy coolguy  166  5월 12 01:23 best_fragment_gen_0.smi
-rw-rw-r-- 1 coolguy coolguy  613  5월 12 01:23 docked_gen_0.csv
-rw-rw-r-- 1 coolguy coolguy 9162  5월 12 01:23 docking_outputs_with_score.sdf
drwxrwxr-x 2 coolguy coolguy 4096  5월 12 01:23 sdf_files
-rw-rw-r-- 1 coolguy coolguy  263  5월 12 01:23 vina_config.txt

./generation_0/sdf_files:
total 36
-rw-rw-r-- 1 coolguy coolguy 1101  5월 12 01:23 f1-dp1.sdf
-rw-rw-r-- 1 coolguy coolguy 1101  5월 12 01:23 f1-dp2.sdf
-rw-rw-r-- 1 coolguy coolguy 1101  5월 12 01:23 f1-dp3.sdf
-rw-rw-r-- 1 coolguy coolguy 1018  5월 12 01:23 f2-dp1.sdf
-rw-rw-r-- 1 coolguy coolguy 1018  5월 12 01:23 f2-dp2.sdf
-rw-rw-r-- 1 coolguy coolguy 1018  5월 12 01:23 f2-dp3.sdf
-rw-rw-r-- 1 coolguy coolguy  935  5월 12 01:23 f3-dp1.sdf
-rw-rw-r-- 1 coolguy coolguy  935  5월 12 01:23 f3-dp2.sdf
-rw-rw-r-- 1 coolguy coolguy  935  5월 12 01:23 f3-dp3.sdf

./generation_1:
total 212
-rw-rw-r-- 1 coolguy coolguy      0  5월 12 01:23 filter.csv
-rw-rw-r-- 1 coolguy coolguy 209910  5월 12 01:23 generation.csv
-rw-rw-r-- 1 coolguy coolguy    649  5월 12 01:23 seed_fragments.smi
```

Contents of "generation.csv" and "seed_fragments.smi" in "result/generation_1" directory are not empty:
```
$ head generation.csv
c1ccccc1,f1-dp1,-4.344,-1.556007975572893,1.0,1.0,c1ccccc1,f1,Na-Na-Na,,3
c1ccccc1,f1-dp1,-4.344,-1.556007975572893,1.0,1.0,O=c1cccnn1-c1ccccc1,PHG_1_M_000000001,G-001-0003,,1
c1ccccc1,f1-dp1,-4.344,-1.556007975572893,1.0,1.0,O=c1ccncn1-c1ccccc1,PHG_1_M_000000002,G-001-0004,,1
c1ccccc1,f1-dp1,-4.344,-1.556007975572893,1.0,1.0,c1ccc(-n2cccc2)cc1,PHG_1_M_000000003,G-001-0051,,2
c1ccccc1,f1-dp1,-4.344,-1.556007975572893,1.0,1.0,c1ccc(C2=NCCN2)cc1,PHG_1_M_000000004,G-001-0084,,1
c1ccccc1,f1-dp1,-4.344,-1.556007975572893,1.0,1.0,Oc1ncc(-c2ccccc2)[nH]1,PHG_1_M_000000005,G-001-0102,,1
c1ccccc1,f1-dp1,-4.344,-1.556007975572893,1.0,1.0,Oc1ncc(-c2ccccc2)o1,PHG_1_M_000000006,G-001-0118,,1
c1ccccc1,f1-dp1,-4.344,-1.556007975572893,1.0,1.0,Nc1cc(-c2ccccc2)ccn1,PHG_1_M_000000007,G-001-0141,,2
c1ccccc1,f1-dp1,-4.344,-1.556007975572893,1.0,1.0,c1ccc(-c2ccco2)cc1,PHG_1_M_000000008,G-001-0151,,2
c1ccccc1,f1-dp1,-4.344,-1.556007975572893,1.0,1.0,c1ccc(C2CC3(CCOC3)C2)cc1,PHG_1_M_000000009,G-003-0009,,1

$ head seed_fragments.smi
smiles_gen_0    id_gen_0        docking score_gen_0     le_ln_gen_0     fitness_gen_0   fitness_rank_gen_0
c1ccccc1        f1-dp1  -4.344  -1.556007975572893      1.0     1.0
c1ccccc1        f1-dp2  -4.34   -1.5545751873817577     0.9970457902511076      2.0
c1ccccc1        f1-dp3  -4.339  -1.554216990333974      0.9963072378138847      3.0
c1ccncc1        f2-dp1  -3.854  -1.3804914221588236     0.638109305760709       4.0
c1ccncc1        f2-dp2  -3.824  -1.3697455107253091     0.6159527326440177      5.0
c1cncnc1        f3-dp1  -3.351  -1.2003183071235646     0.26661742983751846     6.0
c1cncnc1        f3-dp2  -3.328  -1.1920797750245367     0.24963072378138806     7.0
c1ccncc1        f2-dp3  -3.183  -1.1401412030958835     0.14254062038404702     8.0
c1cncnc1        f3-dp3  -2.99   -1.0710091728736073     0.0     9.0
```

Finally here's a list of installed packages in my conda environment:
```
$ conda list -n secse
# packages in environment at /opt/anaconda310/envs/secse:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
biopandas                 0.4.1              pyhd8ed1ab_1    conda-forge
blinker                   1.6.2              pyhd8ed1ab_0    conda-forge
boost                     1.78.0           py38h4e30db6_4    conda-forge
boost-cpp                 1.78.0               h6582d0a_3    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
brotlipy                  0.7.0           py38h0a891b7_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
cairo                     1.16.0            h35add3b_1015    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38h4a40e3a_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
chemprop                  1.5.2              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7            py38hfbd4bf9_0    conda-forge
cryptography              40.0.2           py38h3d167d9_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docstring_parser          0.15               pyhd8ed1ab_0    conda-forge
docutils                  0.16             py38h578d9bd_3    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
filelock                  3.12.0             pyhd8ed1ab_0    conda-forge
flask                     2.3.2              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.39.4           py38h01eb140_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2            py38h793c122_1    conda-forge
greenlet                  2.0.2            py38h8dc9893_0    conda-forge
hyperopt                  0.2.7              pyhd8ed1ab_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.6.0              pyha770c72_0    conda-forge
importlib-resources       5.12.0             pyhd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4            py38h43d8883_1    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.76.2               hebfc3b9_0    conda-forge
libhwloc                  2.9.1                hd6dc26d_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               3.21.12              h3eb15da_0    conda-forge
libsqlite                 3.41.2               h2797004_1    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.5.0                ha587672_6    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.0                h0b41bf4_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.4               hfdac1af_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               16.0.3               h4dfa4b3_0    conda-forge
markupsafe                2.1.2            py38h1de0b5d_0    conda-forge
matplotlib-base           3.7.1            py38hd6c3c57_0    conda-forge
mkl                       2022.2.1         h84fe81f_16997    conda-forge
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.0                hb012696_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
numpy                     1.24.3           py38h59b608b_0    conda-forge
openbabel                 3.1.1            py38h3c5e4c7_5    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.0                hd590300_3    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandarallel               1.6.5              pyhd8ed1ab_0    conda-forge
pandas                    1.5.3            py38hdc8b05c_1    conda-forge
pandas-flavor             0.2.0                      py_0    conda-forge
parallel                  20230322             ha770c72_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pillow                    9.5.0            py38h961100d_0    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
platformdirs              3.5.0              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
protobuf                  4.21.12          py38h8dc9893_0    conda-forge
psutil                    5.9.5            py38h1de0b5d_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py4j                      0.10.9.7           pyhd8ed1ab_0    conda-forge
pycairo                   1.23.0           py38h190342e_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.16          he550d4f_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytorch                   2.0.0           cpu_py38h019455c_0    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
rdkit                     2022.09.5        py38h6600b1c_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reportlab                 3.6.13           py38h57c54bf_0    conda-forge
requests                  2.29.0             pyhd8ed1ab_0    conda-forge
scikit-learn              1.2.2            py38hd4b6e60_1    conda-forge
scipy                     1.10.1           py38h59f1b5f_2    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sphinx                    5.3.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
sqlalchemy                2.0.13           py38h01eb140_0    conda-forge
sympy                     1.11.1          pypyh9d50eac_103    conda-forge
tbb                       2021.9.0             hf52228f_0    conda-forge
tensorboardx              2.2                pyhd3eb1b0_0
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typed-argument-parser     1.8.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
typing_inspect            0.8.0              pyhd8ed1ab_0    conda-forge
unicodedata2              15.0.0           py38h0a891b7_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
werkzeug                  2.3.4              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xarray                    2023.1.0           pyhd8ed1ab_0    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

```
$ vina --version
AutoDock Vina v1.2.1
```

**Comment by ChongLu121** [comment]
Hi @zemanet2020 @sistar2020 ,

We made some updates to the filtering module last Friday that could potentially address the problem you encountered with the empty "filter.csv" file. Once you have the updated code, please test it again to see if the error persists.

Best,
Chong

**Comment by sistar2020** [comment]
I reinstalled SECSE and tried a demo but with the same issue.
So I thought this may be due to version conflicts in some packages or 
to GPU driver problem. Or maybe due to both.

I use Ubuntu 22.04 and nvidia RTX 3090 graphics card.
So, I installed SECSE a bit differently as below:

```
$ git clone https://github.com/KeenThera/SECSE.git
$ cd SECSE
$ conda create --name secse -c conda-forge -c dglteam parallel tqdm biopandas openbabel chemprop xlrd=2 pandarallel rdkit=2022.09 python=3.10 dgl-cuda11.7
$ conda activate secse
#-- check if cuda is available
$ python -c 'import torch;print(torch.cuda.is_available())'
False

#-- download and install dgl-cuda
$ wget https://anaconda.org/dglteam/dgl-cuda11.7/0.9.1post1/download/linux-64/dgl-cuda11.7-0.9.1post1-py310_0.tar.bz2
$ conda install --offline dgl-cuda11.7-0.9.1post1-py310_0.tar.bz2
#-- upgrade torch
$ pip install torch --upgrade
$ python -c 'import torch;print(torch.cuda.is_available())'
True

OK. Now cuda is working fine. Then I ran a demo script:

$ export SECSE=`pwd`/secse
$ export VINA=/usr/local/AutoDock-Vina/bin/vina
$ export AUTODOCK_GPU=/usr/local/AutoDock-GPU/bin/adgpu_analysis

#-- also customize "workdir", "fragments" and "target" to your environments in demo/phgdh_demo_vina.ini file
$ python secse/run_secse.py --config demo/phgdh_demo_vina.ini
```

This job was able to run up to generation_5 as expected and yielded prediction.
Thank you very much for your prompt assistance!
